name: shipaton_wealth_assistant
description: Ship-a-ton mobile AI financial decision assistant.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_chart: ^1.0.0
  file_picker: ^10.3.3
  flutter_tts: ^4.2.3
  http: ^1.5.0
  purchases_flutter: ^10.10.0
  shared_preferences: ^2.5.3
  speech_to_text: ^7.3.0
  supabase_flutter: ^2.10.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
